some optimizations and jitter reduction
AIRLegend/aitrack pull request #148
Opened 2022-07-03 04:05 UTC by searching46dof

OPTIMIZE_Facedata reduces malloc/memcpy from multiple std::string and std::to_string
OPTIMIZE_MAFilter uses this->sum as a cache to optimize calculation of the average in MAFilter::filter
added float suffix f to float constants to so that they are not double and calculations are not promoted to doubles to reduce conversions.
OPTIMIZE_ImageProcessor combines normalize and transpose methods to combine their for loops
FIX_logit_boundary_conditions modifies logit to consistently handle boundary conditions (e.g. > 0.99999f but less than 1.0f)
fix all automatic type conversion warnings with typecasts so that the conversions are visible since they consume CPU.  try to optimize typecast to use float computation but may use double computation in cases required  for the target value type or library function parameter.
OPTIMIZE_Tracker uses a reference to reduce array indexing
OPTIMIZE_PositionSolver reduces the number of double computations by using int64_t computations instead.
DEBUG_OUTPUT_FACE_DATA disables output to std::cout.
FIX_WARNING_PositionSolver fixes a build warning but the original computation trucates the fractional portion. Was it intentional?

2022-07-03 08:11 UTC, AIRLegend requested changes

2022-07-03 08:11 UTC, AIRLegend commented on AITracker/src/model.cpp
> +        float width = (float)image.cols;
is this done because of warnings? the casting is implicit

2022-07-03 08:11 UTC, AIRLegend commented on AITracker/src/imageprocessor.cpp
> +void ImageProcessor::normalize_and_transpose(cv::Mat& image, float* dest, int dim_x, int dim_y)
Cool implementation! 

Just curious, have you measured the gains of using this?

Didn't test it, but if this works okay I think we could remove the directive and use this new method :)

2022-07-03 08:11 UTC, AIRLegend commented on AITracker/src/imageprocessor.h
> +#define OPTIMIZE_ImageProcessor 1
Remove this. The extra method always adds value.

2022-07-03 08:11 UTC, AIRLegend commented on AITracker/src/PositionSolver.cpp
> +        landmark_points_buffer = cv::Mat((int)contour_indices.size(), 1, CV_32FC2);
Because of warnings?

2022-07-03 08:11 UTC, AIRLegend commented on AITracker/src/data.cpp
> +#ifdef OPTIMIZE_Facedata
I don't think this is necessary as this method is mostly for debugging purposes.

2022-07-03 08:13 UTC, AIRLegend commented
Awesome! Thank you very much! ❤️

2022-07-09 02:06 UTC, searching46dof commented on AITracker/src/PositionSolver.cpp
> +#ifdef DEBUG_OUTPUT_FACE_DATA
Yes, VS is using _DEBUG. I was using DEBUG_OUTPUT_FACE_DATA because only the Debug was available from the Configuration pulldown menu. I thought it was very strange since there were other configurations in the xml project.

2022-07-09 02:08 UTC, searching46dof commented on AITracker/src/model.cpp
> +    if (p >= 0.99999f) // prevent divide by zero, with consistent boundary
I added an additional change to use the same resolution for both boundaries.
0.9999999 and 0.0000001
This seems to help improve the jitter as well.

2022-07-09 02:15 UTC, searching46dof commented on AITracker/src/model.cpp
> +        float width = (float)image.cols;
Yes.
One of the ways to optimize is to build with the highest warning levels and fix all warnings including implicit conversions. All conversions would be visible.  Even conversions consume a small amount of CPU.
On some platforms, floating point is internally double so float is actually slower.
On intel with native float support, float is usually faster than double.

2022-07-09 02:27 UTC, searching46dof commented on AITracker/src/imageprocessor.cpp
> +void ImageProcessor::normalize_and_transpose(cv::Mat& image, float* dest, int dim_x, int dim_y)
I'm still trying to profile the changes but it's strange that none of the functions are showing up in various profilers.
I've run it and used it with DCS without any issue.
The overall improvement for all of the changes is approx 1%-2% lower from 7% but this single change is probably less than 1%.
During testing, it appears the cpu util is very dependent on time of day, amount of lighting, the gain and exposure setting, even what is occurring in the background. In order to profile more accurately would require recording and playback of the video stream.
It involves lots of floating point computation where the values matter. The equivalent for ints would be (0x00000000 * non-zero value) vs (0xFFFFFFFF * non-zero value)

2022-07-09 02:30 UTC, searching46dof commented on AITracker/src/imageprocessor.h
> +#define OPTIMIZE_ImageProcessor 1
Using the #ifdef's to easily identify the changes
I wanted to be able to switch the changes on and off for profiling and testing for now.
All of the #ifdef's can be eventually removed

2022-07-09 02:35 UTC, searching46dof commented on AITracker/src/PositionSolver.cpp
> +        landmark_points_buffer = cv::Mat((int)contour_indices.size(), 1, CV_32FC2);
Yes. size() returns size_t.
Fixing all warnings including implicit conversions since they lead to unintended side effects: signed vs unsigned, loss of resolution, etc

2022-07-14 04:11 UTC, closed without merging